name: "dotnet sdk updater"

description: "Update global.json files with the latest SDK version"

author: "xt0rted"

branding:
  icon: "edit"
  color: "purple"

inputs:
  dry-run:
    description: "Checks if an update is available but doesn't update the file."
    required: false
    default: "false"

  file-location:
    description: "The location of the global.json to check."
    required: false
    default: "./"

runs:
  using: "node16"
  main: "dist/index.js"
